"""
My Agent - Generated by Backpack quickstart.
Uses credentials and personality from agent.lock (injected by Backpack).
"""

import os

def main():
    # Credentials are injected by Backpack when you run: backpack run agent.py
    keys = ['OPENAI_API_KEY']
    for key_name in keys:
        value = os.environ.get(key_name)
        print(f"{key_name} available: {'Yes' if value else 'No'}")
    system_prompt = os.environ.get("AGENT_SYSTEM_PROMPT", "")
    print(f"Personality: {system_prompt[:60]}...")
    print("Agent is ready. Replace this with your real logic.")

if __name__ == "__main__":
    main()
